README.md
=> edit: README 2주차 문제추가

README.md
=> Update: 2주차 문제

src/leejaeyeong/Softeer_조립라인.java
재귀를 사용해 매 조립라인에서 **다른 라인으로 이동하는 경우**, **이동하지 않고 그대로 진행하는 경우**를 모두 고려하는 **완전탐색** 방식으로 작성했습니다. 
재귀함수의 파라미터 값으로 생산 진행 횟수, 현재 생산 라인 구분, 소요 시간 정보를 포함하여 구현했는데 테스트 케이스만 맞고 결과는 틀렸네요ㅠ 우선 업로드하고 다시 손보겠습니다 후후😭
=> Create: Softeer 조립라인

src/ashpurple/BOJ_13702_이상한 술집/Main.java
한 사람당 받을 수 있는 최대양을 구하는 문제이다.
양이 매우 작으면 조건을 만족시킬 수 있지만  최대양이 아니므로 최적의 값을 탐색해야한다
처음엔 주전자의 최대 값으로부터 내림차 순으로 조건 `boolean isDivided()` 을 만족하는 값을 찾아나갔는데
이럴 경우 탐색에만 `O(n)`의 시간이 걸려 런타임 에러가 발생했다.
**하지만 우리가 구하려는 최적값은 최적값 이하는 모두 조건을 만족하고 초과는 모두 조건을 만족하지 않는 성질을 갖는다.**
즉 이 값들은 수열의 오름차순과 같은 성질이 있으므로 정렬이 따로 필요없이 이진 탐색을 바로 적용할 수 있다.
중간 값이 조건 `boolean isDivided()` 을 만족할 때는 중간값 이하의 값들은 모두 조건을 만족 시킬 것이므로 다시 탐색 할 필요가 없고 반대의 경우도 마찬가지다.
따라서 이와 같이 이진 탐색을 사용하면 `O(lgn)`으로 탐색시간을 단축시켜 문제를 푸는 것이 가능하다.
(ps. mid값을 구할때 `mid=(max+min)/2` 로 연산을 하였는데 이 때 max와 min이 int 타입이면 overflow가 발생할 수 있었다.)
=> Create: BOJ_13702 이상한 술집 code

src/ashpurple/BOJ_16935_배열돌리기3/Main.java, src/ashpurple/BOJ_2980_도로와 신호등/Main.java
이중 for 문을 이용해 row와 column의 초기값과 조건을 함수에 맞추어 구현하였다.
90도 회전과 같은 경우 row와 column의 size가 바뀔 수 있으니
`rowSize=matrix.length()` `colSize=matrix[0].length()` 와 같이 
해당 함수안에서 재정의 해주는 것이 중요하다.
=> Create: BOJ_16935 Code

src/leejaeyeong/구현/BOJ_16935_배열돌리기3.java, src/leejaeyeong/구현/BOJ_2980_도로와_신호등.java
전역변수로 2차원 배열을 만들고 회전시키는 명령에 따라 배열을 회전한 후 갱신해주는 형태로 짜봤습니다. 문제를 풀면서 연산 시간은 조금 더 걸리지만 쉽고 빠르게 풀 수 있는 방법이 생각나서 공유합니다.   
`3번과 4번` : 오른 쪽으로 90도 회전하는 3번 명령을 이용해 4번 명령을 바로 구현할 수 있습니다. 
- 4번 명령이 입력되면 3번 명령을 3번 수행
`5번과 6번` : 이 명령은 푸는 방식에 따라 달라질 수도 있을 것 같은데, 저는 위와 마찬가지로 6번 명령이 들어올 경우 5번 명령을 3번 실행하여 6번 명령과 같은 결과를 냈습니다. 
- 6번 명령이 입력되면 5번 명령을 3번 수행
**제 코드에는 6번 결과를 내는 부분에만 위 방법을 적용했습니다.**
=> Update: 배열 복사 내장 함수에 대한 주석 추가

src/ashpurple/BOJ_2980_도로와 신호등/Main.java
출발과 동시에 모든 신호등이 빨간불로 시작합니다.
따라서 신호등 cycle은 크기는`R+G`이고 
자동차가 도착한 시간을 cycle 크기로 나눈 나머지 `time%(R+G)`가 R이하이면 빨간불입니다.
빨간불인 경우 R-(time%(R+G)) 만큼 기다립니다.
그렇게 time과 현재위치 `curLoc`를 갱신해가며 
마지막엔 time에 도로길이에서 현재위치를 뺀값인 `distance-curLoc`을 더해주며 마무리 합니다.
=> Create: BOJ_2980 Code

src/leejaeyeong/구현/BOJ_도로와_신호등.java
🚦 도로의 거리와 신호등 사이의 **거리 간격을 반복적으로 계산**해주고, **최근 위치를 갱신**해주는 방법으로 접근했습니다. 
🚦 현재까지 소비한 시간과 신호등의 빨간불, 초록불의 지속시간을 계산해 **지연 시간을 누적**해줬고, 
🚦 마지막 신호등과 끝 지점은 반복문 내부에서 처리가 안되므로 출력부분에 따로 연산을 추가해서 해결했습니다.
=> Create: BOJ 도로와 신호등

src/oteosuk/상금 헌터.py
첫 PR 이고 늦류 죄송합니다 ㅎㅎ..
코드는 유일하게 조금이나마 사용가능한 파이썬을 사용하였으며
첫번째 페스티벌과 두번째 페스티벌, 각각에 등수에 따른 상금 반환하는 함수를 한개씩 작성하고
그 두개를 더한 값을 출력하는걸 여러번 반복하는 식으로 짰습니당
=> Create: BOJ 15953 PrizeHunter source code

src/oteosuk/조립 라인.py
메인아이디어는
일단 a공장에 도착하는 두가지 경우,  (a->a,b->a)에서 둘중 최적값(작은값)을 도출하고
그다음 b공장도 마찬가지로 (b->b, a->b)에서 둘중 최적값(작은 값)을 도출한후 
그 두 최적값을 비교하여 최종 최적값을 구하는 식으로 구성
N > 3 일 경우 리스트를 이용해서 입력을 여러번 한꺼번에 받아놓고(4개입력하는 파트부분만)
마지막에 2개만 입력하는 방식으로 했습니다.(마지막은 공장이동시간이 불필요하므로)
백준처럼 정답인지 채점해주진 않아서 정답인지는 모르겠지만, 여러가지 경우 입력했을때 잘 출력하였고
제한시간 2초, 제한메모리 256mb 인데,  105ms  37.03mb 나온걸 보니 이정도면 합격인듯..? ㅈㅅ
구성한 것을 코드로 바꾸려니까
굉장히 골머리 때렸던 문제였네요,
좋은 경험이 된 문제입니다.
=> Create : Softeer 조립라인

src/hanabzu/BOJ_11387_님무기가좀나쁘시네여/main.cpp
* **Class definition**
5가지의 각 수치를 멤버로 갖는 클래스 `Stat`을 선언하고, **operator overloading**을 통해 무기 교체로 바뀌는 수치를 간단히 처리할 수 있게 하였습니다. 전투력은 `compute_pow()` 함수로 구합니다.
미리 정의된 클래스의 오브젝트끼리 +, - 연산을 하면 아래와 같이 모든 수치를 한번에 계산한 결과를 얻을 수 있습니다.
```
float differ_Cri = Cri.compute_power() - (Cri - weapon_Cri + weapon_Fav).compute_power(); // Cri의 전투력 변화량
```
=> Create: BOJ_11387_님무기가좀나쁘시네여 source code

src/ashpurple/BOJ_11387_님무기가좀나쁘시네여/Main.java
피드백 반영하여 수정 완료했습니다.
실수형 계산을 할 때 오차를 주의 해야된다는 걸 깨달았네요.
=> Create: BOJ_11387_님무기가좀나쁘시네여 code

src/ashpurple/BOJ_10434_행복한  소수/Main.java
소수와 행복한 수의 수학적 연관성이 없는 것 같아 두 상태를 독립적으로 계산했습니다.
**소수판별**
- `if num % 2 == 0` 조건으로 짝수를 걸러주었습니다
- 그 외는 `for(int i = 3; i <= Math.sqrt(num); i+=2)`  루프를 돌며
3부터 제곱근까지의 홀수만  `if(num % i == 0)` 조건으로 체크했습니다.
2이상의 모든 수는 제곱근 보다 작은값과 큰값의 곱으로 나타낼 수 있으므로 이를 이용하면
불필요한 계산을 피해 `O(n^(1/2))` 만큼이 걸려 탐색시간을 단축시킬 수 있습니다.
**행복한 수 판별**
제곱의 합연산을 반복할때 이전 값과 같은 값이 나오게 되면 무한 loop에 갇히는 상태가 됩니다.
이 상태일 때 그 값은 절대 행복한 수가 될 수 없으므로 이를 dp를 이용해 해결했습니다.
sum 값들을 HashSet에 저장한 후 이미 저장한 값이 나오거나 sum이 1이 될 때를 종료조건으로 설정했습니다.
=> Create: BOJ 10434 행복한소수 code

src/leejaeyeong/수학/BOJ_10343_행복한소수.java
2부터 약수일 가능성이 있는 최대값 sqrt(n)까지 나누어떨어지는 수가 있는지 확인하면서 소수를 판별했습니다. 2 ~ sqrt(n) 범위에서 n과 나누어 떨어지는 수가 있으면 n은 소수가 아닙니다. 
행복한 수를 구하는 과정에서 얻은 값을 Set에 저장해놓은 후, 이후에 같은 값이 나오면 현재까지 나온 수 범위에서 루프를 돌기 때문에 더 이상 연산을 수행할 필요가 없으므로 반복을 빠져나왔습니다.
=> Create: BOJ 10343 행복한 소수

src/hanabzu/Softeer_복잡한조립라인2/main.cpp
먼저 첫번째 라인의 작업장들의 작업 시간을  `int* work = new int[K];`로 선언한 배열에 저장 합니다.
for문을 통해 N-1번의 루프를 돌며 integer 변수 `move`에 작업장 변경 시간을 저장 후,
STL algorithm 헤더의 `min_element()` 함수를 사용해 `work` 배열에서 작업장 변경 시간을 더한 최솟값을 구해 `local_min`에 저장합니다.
그 다음으로 내부 for문으로 모든 `work `배열의 원소를 돌며 `local_min`과 `work[K]`를 비교해 최솟값으로 갱신합니다.
동시에 다음 `work`값도 읽어 더해줍니다.
위 내용을 모두 반복 후에 `work`배열에 저장된 값들은 각 K번째 인덱스 작업장으로 작업을 끝마치는 최소 작업 시간입니다.
이 작업 시간들 중 최솟값이 global minimum입니다.
=> Create: Softeer_복잡한 조립라인2 source code

src/leejaeyeong/Softeer_복잡한_조립라인2.java
🔔 **복잡한 조립라인2 종칩니다.** 
구현한 풀이 방법은 각 라인의 작업을 진행할 때, 이전 작업을 다른 라인에서 하고 이동해온 경우, 라인이 변경되지 않은 경우 중 
더 짧은 경우를 선택해서 현재 시점에서의 작업 시간을 누적하는 방법으로 짰습니다.
처음에 input data를 2차원 배열에 저장한 후 사용하는 방법을 썼는데, 실행시간이 2.08초가 나와서 실패했습니다.
저장 후 사용하는 배열을 2차원에서 1차원으로 변경하고 실행한 결과 실행시간은 개선됐지만 결과는 여전히 틀렸습니다.
별도로 만든 테스트케이스도 맞는 답을 출력하는 상황이라 어떤 부분이 문제인지 찾기가 어렵네요ㅠ
=> Create: Softeer 복잡한 조립라인2 source code

src/DW-K/BOJ-15953번 - 상금 헌터/week1.cpp
각 페스티벌의 등수에 따른 상금의 규칙성을 활용하여 간결하게 코드를 작성했습니다.
=> Create: BOJ-15953번 - 상금 헌터 code

src/oteosuk/배열 돌리기3.py
이중리스트를 이용해 배열을 구현하였습니다.
상하반전과 좌우반전은 간단히 reverse()함수와 슬라이싱으로 구현하였고,
나머지 돌리기와 그룹이동은
n x m 크기의 0으로 채워진 빈 이중리스트를 만들어서 거기에 하나하나 규칙적으로 채우는 식으로 구현하였습니다.
=> Create: BOJ_16935_배열돌리기3 code

src/DW-K/BOJ-13702번 - 이상한 술집/week3.cpp
binary search 를 사용하여 구현했습니다.
파이썬으로 먼저 코드를 작성하고 그대로 C++로 옮겼습니다.
파이썬은 테스트를 통과했지만 C++ 코드는 계속 실패하네요ㅠㅠ
도움 요청합니다..ㅠ
---
수정했습니다! 정상적으로 통과되네요. 자료형 문제였습니다.
=> Update : BOJ - 13702번 - 이상한 술집 Code

src/ashpurple/BOJ_6568_귀도 반 로썸은 크리스마스날 심심하다고 파이썬을 만들었다/Main.java
컴퓨터 구조에 대해서 배우지 않아 기본적인 레지스터 연산 관련 내용을 참고하여 선행학습 한 뒤에 문제를 풀었습니다.
기본 자료형은 int 형으로 2진수를 10진수로 변환하여 계산하였고 divide 와 modular 연산은 비트 연산자로 수행했습니다.
무한 루프 내에서 `EOF`가 나올 때 까지 한 cycle의 메모리를 반복해서 입력받았고
한 단위의 메모리에서 `HLT `명령어가 나올 때 까지 반복 연산을 실행합니다.
이 과정에서 pc와 adder는 모두 5비트와 8비트로 메모리가 한정적이기 때문에 modular 연산을 해주었고
한 cycle이 끝나면 모두 0으로 초기화 해주어 다시 연산을 수행하는 시퀀스 입니다.
=> Create: BOJ_6568_귀도 반 로썸은 크리스마스날 심심하다고 파이썬을 만들었다 Code

src/hanabzu/BOJ_6568_귀도반로썸은크리스마스날심심하다고파이썬을만들었다/main.cpp
+ ### data structure
memory는 `bitset<8>`의 배열로, adder와 program counter는 `unsigned char`로 선언하여 구현하였습니다.
이렇게 입력받은 이유는 입력은 `bitset`으로 받아야 쉽기 때문이지만, arithmetic operation은 `bitset`이 좀 불편하기 때문에 직관적인 `unsigned char`형으로 혼용해 사용하였습니다.
이 외에 instruction을 address와 op로 나누는 데에도 `unsigned char`를 사용하였고, adder를 memory에 저장하거나 출력하기 쉽도록 bit_adder로 `bitset`으로 변환한 변수 또한 각 instruction마다 선언해 사용하였습니다.
---
+ ### read_case()
먼저 처음엔 case가 한 개인 줄 알았지만 여러 개의 case가 입력될 수 있으므로 `read_case()`라는 함수를 선언하여 EOF를 입력으로 받을 때까지 반복하였습니다.
`read_case()` 함수 내부에서는 먼저 32개의 instruction을 memory에 입력받습니다.
그후 adder와 pc를 0으로 초기화하고  `while`문을 통해 intruction을 하나씩 읽어 실행합니다.
먼저 op와 address를 비트연산을 통해 구해준 후 pc에 1을 더합니다. (이 때, pc는 5 bits 이므로 modular를 사용합니다.)
`switch`문을 사용해 op code에 따라 동작합니다.
메모리에 adder를 저장하는 STA나 프로그램을 마치는 HLT에서는 bitset constructor를 …
=> Create: BOJ_6568_귀도 반 로썸은 크리스마스날 심심하다고 파이썬을 만들었다 source code

src/ashpurple/BOJ_7569_토마토/Main.java
BFS를 활용해 최종 Depth를 구하는 문제입니다.
초기에 익은 토마토가 여러개 주어질 수 있기에 root node는 여러개일 수 있습니다.
따라서 초기 node들을 전부 리스트에 저장하고 **bfs 함수**에 인자로 전달합니다.
이 때 리스트에 저장된 자료형은 좌표를 저장하고 있어야 하기 때문에 `Tomato`라는 class 형식으로 구현했습니다.
bfs 함수에서는 `boolean isValid()`라는 메소드를 사용하여 조건을 만족할 때만 queue 에서 pop을 해주고 visit 처리를 해주었습니다.
**_하나의 cycle은 초기 queue의 사이즈 만큼 반복하며 cycle은 depth를 의미합니다._**
따라서 한번의 cycle마다 day 값은 1씩 증가합니다.
Queue와 linked list, BFS, for each 문, class 등 모두 자바에서 써보지 않은 것들인데
최대한 다양한 방식을 시도하며 푸는데 초점을 두었습니다
=> Create: BOJ_7569_토마토 Code

src/DW-K/BOJ-16935번 - 배열 돌리기3/week4.cpp
1. 상하를 반전 시키는 1번 연산은 포인터 주소를 바꿔서 해결했습니다.
2. 좌우를 반전 시키는 2번 연산은 직접 값을 바꿔 주었습니다.
3. 추가적인 temp 배열을 만들지 않고 풀어보려 했으나 너무 복잡하여
3~6번 연산은 temp 배열을 이용하여 해결했습니다.
=> Create: BOJ - 16935번 - 배열 돌리기3 code

src/DW-K/BOJ - 2980번 - 도로와 신호등/week5.cpp
메모리를 아끼기 위해 신호등의 정보를 받는대로 처리하였습니다.
logic의 기본 개요는 신호등이 있는 위치까지 이동한 뒤 : `time += D - PD;`
빨간불인지 판별 후  `if (RT < R || RT > C)`
초록불이 되는 시간이 되면 이동하는 것입니다. `time += R - RT;`
=> Create : BOJ - 2980번 - 도로와 신호등 code

src/DW-K/BOJ - 11387번 - 님 무기가 좀 나쁘시네여/week6.cpp
=> Create : BOJ - 11387번 - 님 무기가 좀 나쁘시네여 code

src/ashpurple/BOJ_2533_사회망 서비스(SNS)/Main.java
트리에서 DFS 를 진행하며 DP 를 이용해 풀이하였습니다.
알고리즘은 전제 조건이 성립할때만 문제없이 작동됩니다.
-  모든 노드는 edge가 존재하며 사이클이 존재하지 않습니다. 
=> 즉 입력 순서에 상관없이 어떤 노드부터 탐색을 진행하는든 결과 값은 같게 나옵니다.
-  정점의 개수 N은 2 이상입니다.
- `LinkedList<Integer>[] edge`: 해당 인덱스[u]에 연결된 정점의 값[v]를 갖는 LinkedList입니다. empty를 방지하기 위해 양방향으로 구현하였습니다.
- `boolean[] visit`: 해당 노드의 방문 여부를 체크합니다.
- `int[] normal`: index에 해당하는 노드가 일반노드(얼리어답터가 아닌 노드)라 가정할 때 연결된 child 노드 부터 현재 노드까지의 얼리어답터의 수를 의미합니다.
- `int[] early`: index에 해당하는 노드가 얼리어답터라 가정할 때 연결된 child 노드 부터 현재 노드까지의 얼리어답터의 수를 의미합니다.
- 초기값: 정점이 두개 이상일 때를 가정하므로 leaf node의 normal은 0으로 초기화 합니다.
`early = 1; normal = 0;`
- 현재 노드가 normal 일 경우 자식 노드는 모두 early 상태가 되야하므로 자식의 early 값을 더해줍니다.
`normal[cur] += early[child]`
- 현재 노드가 early 일 경우 자식이 early일 경우와 normal 경우 중 최소값을 더해줍니다
`early[cur] += min(normal[child], early[child])` …
=> Create: BOJ_2533 사회망 서비스(SNS) Code

src/DW-K/BOJ - 10434번 - 행복한 소수/week7.cpp
Vector를 사용하여 Split Int 함수를 구현했습니다.
각 자리수를 제곱하여 더하는 과정이 1이 나오지 않으면 무한히 반복되어서 종료 조건 어떻게 해야할지 고민했었는데
문제에서 7이 가장 작은 행복한 소수라고 주어져서 7보다 작을 경우 반복을 종료하도록 작성하였습니다.
=> Create : BOJ - 10434번 - 행복한 소수 code

src/ashpurple/BOJ_10830_행렬 제곱/Main.java
행렬의 제곱 연산은 하위 연산으로 쪼개는 것이 가능합니다.
예를 들어 A^8 = A^4 * A^4 = A^4 * A^2 * A^2 = A^4 * A ^2 * A * A 와 같이 sub problem 으로 나눌 수 있습니다.
따라서 연산 과정이 적절히 나뉜다면 A^8에서 단순히 A를 8번 곱하는 계산을
`A * A` ->`A^2 * A^2` ->`A^4 * A^4` 이렇게 3번의 계산으로 줄일 수 있습니다. `O(N)`->`O(lg N)`
분할은 재귀 함수내에서 다음 3가지 조건 내에서 실행됩니다
- 1 제곱일 때: A 를 return
- 짝수 제곱일 때: `A^(n/2) * A^(n/2)`
- 홀수 제곱일 때: `A^(n-1) * A `
=> Create: BOJ_10830 행렬 제곱 Code

src/leejaeyeong/분할정복/BOJ_10830_행렬_제곱.java, src/leejaeyeong/완전탐색, dfs, bfs/BOJ_2533_사회망_서비스.java
거듭제곱의 지수 r이
**짝수일 때**는 `A^r = A^(r/2) * A^(r/2)`, 
**홀수일 때**는 `A^r = A^(r-1) * A`과 같이 표현하여 문제를 작게 쪼개어 해결하는 **분할정복 알고리즘**을 적용했습니다. 
큰 문제를 작은 단위로 분할하여 해를 구하고, 분할 문제에 대한 해를 이용해 연쇄적으로 그 다음 문제들의 해를 구하여 
최종 답을 구했습니다.
=> Create: BOJ_10830_행렬_제곱 source code

src/hanabzu/BOJ_10830_행렬제곱/main.cpp
input matrix의 제곱, 제곱의 제곱 등을 table에 저장합니다.. (A, A^2, A^4, A^8 .....)
그 B를 bitset으로 이진수로 바꾼 후 이진수 값중 1에 해당하는 (즉, B를 2의 거듭제곱들의 합으로 나누었을 때 존재하는 수들) table의 matrix들을 곱하여 결과를 구합니다.
2^36 < 100,000,000,000 < 2^37 이므로 table은 37개를 구해둡니다.
=> Create: BOJ_10830 행렬제곱

src/leejaeyeong/완전탐색, dfs, bfs/BOJ_9207_페그_솔리테어.java
이동할 수 있는 핀의 모든 경우에서 dfs 함수를 호출합니다. 
핀의 이동 조건을 만족하는 경우 맵의 상태를 변경하고 파라미터로 
- **핀의 개수**
- **움직인 수**
- **맵의 상태**  
등의 정보를 전달하는 방식으로 구현했습니다. 
dfs를 호출하고 돌아오면 맵을 원 상태로 복구해줬습니다.
=> Create: BOJ 9207 페그 솔리테어 source code

src/hanabzu/BOJ_9207_페그솔리테어/main.cpp
Solution of this problem must scan all possible cases of moving pins.
When a game keeps going (any pin could be moved somewhere), we don't know whether **"a current journey route"** is the best or not. so we should **find & try all cases**.
---
`dx[4], dy[4]` is the commonly used matrix position scan arrays. 
`N` is a number of test cases.
`num_pin, num_moving` is the best case's minimum statements for print result.
`table[7][11]` is a table of pins with **a padding**.
---
I implemented a recursive function `solve(int rest, int depth)` for DFS search with brute force and back tracking.
`rest` is the number of pins left in the table. `depth` is the turn count.
`solve()` functions scans all positions of the tables until **finding a movable pin**. to check within this process, …
=> Create: BOJ_9207 페그 솔리테어

src/DW-K/Softeer - 복잡한 조립라인2/week8.cpp
N 과 K를 혼동하여 문제 해결에 어려움이 많았습니다..ㅠ
=> CREATE : 복잡한 조립라인2 Code

src/hanabzu/BOJ_2352_반도체설계/main.cpp
O(n^2)의 시간복잡도로는 통과할 수 없으므로 이진 탐색을 이용하여 설계하였고 다음 블로그를 참조하였습니다.
[https://shoark7.github.io/programming/algorithm/3-LIS-algorithms#4](https://shoark7.github.io/programming/algorithm/3-LIS-algorithms#4)
=> Create: BOJ_2352 반도체 설계

src/ashpurple/BOJ_20061_모노미노도미노2/Main.java
구현의 중점은 Green Board와 Blue Board에 대한 함수들을 따로 나누지 않고
파라미터만 다르게 주어 함수의 중복을 최소화하는데 두었다.
함수 통일 방법
- Green Board와 Blue Board는 모두 6행 4열의 배열로 구성했다
- drop 에서 green은 y 기준 blue는 x 기준으로 좌표를 대칭 시켰다
- drop에서 t는 blue기준으로 2와 3을 switch 해주었다. (blue에서 t=2 는 1*2 타일)
프로세스
1. drop : 타일을 떨어트린다
2. pop : 꽉 찬 행이 존재하지 않을 때까지 해당 행을 비우고 옮겨준다 (스코어)
3. special pop : 연한 칸에 타일이 존재하지 않을 때 까지 가장 밑층을 비우고 옮겨준다
함수
- `void drop(boolean[][] board, int y, int t)`
: 위 층부터 차례로 체크하여 적절한 위치에 타일을 떨어트린다
- `int getFullIndex(boolean[][] board)`
: 가득찬 행을 체크하여 해당 행의 index를 반환한다
- `void move(boolean[][] board, int y)`'
: y 층을 비우고 y 위층들을 아래로 옮긴다
- `void popAndMove(boolean[][] board)`
: `getFullIndex`로 가득찬 행이 확인 되면 해당 행을 `move`로 비우고 옮겨준다
- `boolean isLight(boolean[][] board)`
: 연한 색 보드에 타일이 존재하는지 체크한다
- `void countTile()`
: 전체 타일의 개수를 카운트한다
=> Create: BOJ_20061_모노미노도미노2 Code

src/hanabzu/BOJ_20061_모노미노도미노2/main.cpp
It helps to delete rows from the table easily.
I implemented the row index of tables in the problem contrarily. Whenever the row deleted in the table, just use `erase()` method of STL vector and `push_back()` a new row.
This solution makes the implementation of `checkLine()` function very simple.
`count()` method in STL algorithm header is used to count blocks.
=> Create: BOJ_20061 모노미노도미노 2

src/hanabzu/BOJ_2156_포도주시식/main.cpp
`dp[3][10000]` array is a 3-d table to get max value at each sum of capacity of wine.
`dp[0][i]` stores the max capacity of wine up to the i-th **not drinking the i-th wine.**
`dp[1][i]` stores the max capacity of wine up to the i-th **not drinking the (i-1)-th wine, but drinking the i-th wine.**
`dp[2][i]` stores the max capacity of wine up to the i-th **drinking the (i-1)-th wine and i-th wine.**
so this rule stores always the maximum at the array's last index.
=> Create: BOJ_2156 포도주 시식

src/ashpurple/BOJ_2156_포도주 시식/Main.java
점화식을 세워 dp로 풀이하였다.
- dp[N]: N 번째 포도주까지 마실 수 있는 최대값
- drink: N 번째 포도주를 마셨을 때 누적 최대값 
`max( dp[N - 2] + wine[N], dp[N - 3] + wine[N - 1] + wine[N] )`
-> 직전에 마시지않았을 때와 직전에 마셨을 때 중 최대값
- no_drink: N 번째 포도주를 마시지 않았을 때 누적 최대값
`dp[N - 1]` 마시지 않으면 직전 dp 값과 같다
- dp[i] = `max(drink, no_drink)` 위 둘 중 최대값
=> Create: BOJ_2156_포도주 시식 Code

src/ashpurple/Programmers_베스트앨범/Solution.java
ArrayList와 HashMap 그리고 calss를 이용하여 구현하였다.
1. 장르와 재생횟수 리스트를 이용해 곡의 정보를 담은 객체들을 생성한다.
2. 객체 생성과 동시에 해시맵을 이용해 장르에 따른 총 재생횟수를 저장한다. 
3. 해시맵을 key값을 기준으로 정렬해 상위 2개(또는 1개) 장르를 `String[] topGenre`에 저장한다 .
4. 객체들을 재생횟수 내림차순으로 정렬한다.
5. `topGenre` 순으로 for문을 돌며 정렬된 객체에서 장르에 해당되는 상위 2개(또는 1개) 곡 번호를 저장하고 출력한다.
- 해시맵 정렬은 ArrayList로 변환한뒤 Entry를 이용한 Collections의 메소드로 정렬해주었다.
- 객체 정렬은 `implements Comparable<>`을 이용해 `compareTo`를 override 하였다.
=> Create: Programmers_베스트앨범 Code

src/hanabzu/Programmers_베스트앨범/solution.cpp
A definition of data strucures for this problem is very important.
At first, playing counts of each genres are needed. `map<string, int> played` stores each genres' played count.
Second, in each genres, songs are also sorted by played count. `map<string, set<pair<int,int>, set_cmp>> songs` stores them.
In this map `songs`, a key is genres name. a value is set of each songs composed of a pair of a song's played count and an index.
And `set_cmp` is a struct to sort each songs by what I want. (A played count has a priority than a song index)
First `for` statement stores datas to data structures.
Than convert `played` to vector container to sort by value.
Second `for` statement pushes top played songs to the answer.
=> Create: programmers 베스트 앨범

src/ashpurple/Programmers_퍼즐 조각 채우기/Solution.java
블럭 하나에 대해 비교가능한 최소단위의 고유한 행렬을 만든다 (블럭에 테두리만 감싸는 행렬)
만들어진 블럭(행렬)을 회전시켜가며 비교한다
1. game_board의 값을 반전 시킨다
2. game_board와 table에서 블럭들을 추출해 각각 리스트에 저장한다
3. 보드블럭에 대해 테이블 블럭들을 비교한다
3.1 두 블럭이 일치하지 않을 경우 테이블 블록을 90도 회전시켜 다시 비교한다
3.2 회전값 4번에 대해 모두 일치하지 않으면 다음 보드블럭과 비교한다
3.3 일치할 경우 block.num 값을 정답값에 더해주며 테이블 블럭을 리스트에서 제거하고 다음 루프로 점프한다
- `boolean isMatch(Block a, Block b)` : 두 블럭이 같은 블럭인지 비교한다. 시간 단축을 위해 개수와 row, col 값을 먼저 비교한다
- `void rotateBlock(Block block)` : 해당 블록을 90도 회전 시킨 값을 블럭에 업데이트 시킨다
- `Block bfs(int[][] board, int x, int y)` : bfs를 이용해 상하좌우로 연결된 값들을 리스트에 저장하며 `makeBlock`을 호출한다
- ` Block makeBlock(int minX, int minY, int maxX, int maxY, ArrayList<Point> pointList)` : 파라미터 값을 이용해 블럭을 생성한다
=> Create: Programmers_퍼즐 조각 채우기 Code

src/hanabzu/Programmers_퍼즐조각채우기/solution.cpp
A Block object is a single connected block of multiple dots. The one single object has all coordinate point set and block size. (Also, bool variable `used` means whether or not it was used at `match_blocks()` function)
-  **void add_point(point p)** 
`point` is defined user type variable (`pair<int,int>`).
This method adds adds a point to the set that makes up this block and does size+1.
- **void rotate()**
This method rotates all points of this block 90 degrees.
And **very important feature** is, the first point in `set<point>` must be (0,0).
So after rotation, minus `bias`(a first point's coordinate in new rotated set) to all points.
This process helps a comparison between to blocks more easier. 
(Just compare all points of two blocks. they're in `set` container, so if two blocks are …
=> Create: programmers 퍼즐 조각 채우기

src/ashpurple/Programmers_순위/Solution.java
순위를 알기위해선 각 정점에 대한 모든 연결관계를 알아야한다.
따라서 그래프 알고리즘 중 **모든 정점에대한 연결성**을 알 수 있는 플로이드와샬 알고리즘을 변형해서 사용하였다.
거리 비교 대신 간접적인 승패의 대한 정보를 boolean 형식의 matrix에 업데이트 했다.
예를 들어 A가 B를 이기고 B가 C를 이겼다면 A는 C를 간접적으로 이긴 것이므로 matrix[A][B] 와 matrix[A][C]는 모두 true가 된다.
`if (matrix[i][k] & matrix[k][j] ) matrix[i][j] = true;`
- false로 초기화된 n * n 행렬을 만들고 초기 승패 정보를 저장한다 (A win B -> matrix[A][B] = true)
- 플로이드워샬 알고리즘을 이용해 간접적인 연결관계를 업데이트한다
- 한 노드가 모든 노드에 대해서 연결돼있을 경우 순위가 정해지므로 정답케이스로 count한다
=> 여기서 연결의 정의는 승패(A->B, B->A)를 모두 포함한다
=> Create: Programmers_순위 Code

src/hanabzu/Programmers_순위/solution.cpp
Make n by n matrix and write down who is winner.
Using floyd-warshall algorithm, update matrix.
And count zero on each line.
=> Create: programmers 순위
